# Generated by Django 2.2.9 on 2021-11-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211022_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=400, verbose_name='тест'),
        ),
    ]
