# Generated by Django 2.2.16 on 2021-12-13 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211213_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 13, 12, 10, 44, 405432, tzinfo=utc)),
        ),
    ]
